title: Rémy Deshayes
logo: /assets/img/pp_london.jpeg
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
url: "https://remydeshayes.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
